version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment: 
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: db
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: unless-stopped

  app:
    image: tostole/compdistapp
    container_name: app
    ports:
      - 8081:8080
    environment:
      SECRET_KEY: d5zmAsUt3bZdZrBjhcpJ7T2ocQgmVXfM
      DATABASE: mysql+pymysql://root:123@mysql:3306/db
    volumes:
      - ./docker/sqlite:/app/instance
      - ./docker/log:/app/log
    depends_on: 
      - mysql
    links:
      - mysql
    restart: unless-stopped

networks:
  mysql_network:
    name: mysql_network